# FYI >>> following all this and other files from this source: https://www.digitalocean.com/community/tutorials/how-to-automate-deployments-to-digitalocean-kubernetes-with-circleci

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: default
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image:  nathanbenton/flask-app-foo:${COMMIT_SHA1}
          ports:
            - containerPort: 30000
              name: wtf
              