apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
    - port: 30000
      nodePort: 30000
      name: node-port-flask
      protocol: TCP
  selector:
    app: flask-app
    