apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: default
  labels:
    app: nginx-app
spec:
  type: ClusterIP
  ports:
    - port: 30000
      nodePort: 30000
      name: node-port-flask
      protocol: TCP
  selector:
    app: nginx-app    