apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  selector:
    matchLabels:
      name: mongo-pv
  accessModes:
    - ReadWriteMany 
  volumeName: pv-mongo
  resources:
    requests:
      storage: 1Gi
